### ISSUE TITLE
Server error: NotImplementedError: Python version None is currently not supported.

### ISSUE THREAD

**Issue by dmankins** [pythonic-emacs/anaconda-mode#380]
Hi, 

I've been plagued with the error message showing up in my message window:

"Server error: NotImplementedError: Python version None is currently not supported."

It turns out one of my anaconda environments has recently moved to Python 3.8.

Here's the contents of my *anaconda-mode* buffer (the existence of which I found when google took me to a page describing another issue --- even though I _now_ see it's mentioned among the things to report if one is opening an issue):

`Traceback (most recent call last):
  File "/home/dm/.emacs.d/anaconda-mode/0.1.13/parso-0.3.1-py2.7.egg/parso/grammar.py", line 236, in load_grammar
    return _loaded_grammars[path]
KeyError: '/home/dm/.emacs.d/anaconda-mode/0.1.13/parso-0.3.1-py2.7.egg/parso/python/grammar38.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dm/.emacs.d/anaconda-mode/0.1.13/parso-0.3.1-py2.7.egg/parso/grammar.py", line 239, in load_grammar
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dm/.emacs.d/anaconda-mode/0.1.13/parso-0.3.1-py2.7.egg/parso/python/grammar38.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dm/.emacs.d/anaconda-mode/0.1.13/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
  File "/home/dm/.emacs.d/anaconda-mode/0.1.13/jedi-0.13.1-py2.7.egg/jedi/api/__init__.py", line 95, in __init__
    self._grammar = parso.load_grammar()
  File "/home/dm/.emacs.d/anaconda-mode/0.1.13/parso-0.3.1-py2.7.egg/parso/grammar.py", line 250, in load_grammar
    return load_grammar(**kwargs)
  File "/home/dm/.emacs.d/anaconda-mode/0.1.13/parso-0.3.1-py2.7.egg/parso/grammar.py", line 246, in load_grammar
    raise NotImplementedError(message)
NotImplementedError: Python version None is currently not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dm/.emacs.d/anaconda-mode/0.1.13/service_factory-0.1.5-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/dm/.emacs.d/anaconda-mode/0.1.13/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/dm/.emacs.d/anaconda-mode/0.1.13/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/dm/.emacs.d/anaconda-mode/0.1.13/service_factory-0.1.5-py2.7.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "NotImplementedError(\'Python version None is currently not supported.\')"}}')
`

Seeing the KeyError instead of the NotImplementedError would have gotten me to fix my problem faster, but I don't expect that is easy to do in a general way that would be universally helpful.

What I *do* think is both easy (and helpful even for elisp-averse users) is for the message to include: "See buffer *anaconda-mode* for more information." as part of the message.

A simple alternative might be to add to the FAQ that "Many problems may be solved by looking at the *anaconda-mode* buffer in your EMACS."

Thanks!

**Comment by CeleritasCelery** [comment]
So if I understand correctly, you resolved the issue but think it would be good to update the error message to point to the ananconda buffer?

**Comment by dmankins** [comment]
Yes, that's right.  I suppose you could view it as a feature request that
would make it easier to diagnose and fix problems like the one I had.
