### ISSUE TITLE
Anaconda-mode  ValueError

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [pythonic-emacs/anaconda-mode#388]
I`m using 
python 3.6
jedi 0.17
anaconda 0.1.13
Emacs version Doom Emacs

```
anaconda_mode port 40787
<string>:99: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
<string>:99: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
<string>:155: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_signatures instead.
<string>:131: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).complete instead.
<string>:99: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
<string>:99: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
<string>:155: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_signatures instead.
<string>:131: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).complete instead.
127.0.0.1 - - [19/May/2020 10:31:13] ================================================================================
Traceback (most recent call last):
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
  File "<string>", line 126, in company_complete
  File "<string>", line 128, in <listcomp>
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.17.0-py3.8.egg/jedi/api/classes.py", line 675, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.17.0-py3.8.egg/jedi/api/classes.py", line 262, in docstring
    doc = self._get_docstring()
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.17.0-py3.8.egg/jedi/api/classes.py", line 684, in _get_docstring
    return super(Completion, self)._get_docstring()
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.17.0-py3.8.egg/jedi/api/classes.py", line 273, in _get_docstring
    return self._name.py__doc__()
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.17.0-py3.8.egg/jedi/inference/compiled/value.py", line 329, in py__doc__
    value, = self.infer()
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "ValueError(\'not enough values to unpack (expected 1, got 0)\')"}}')
```

**Comment by dakra** [comment]
What exactly are you doing to get this error?

**Comment by PhilippeNoel1** [comment]
Same problems for me.
jedi 0.17.2
anaconda-mode 0.1.14

```
anaconda_mode port 33429
127.0.0.1 - - [22/Jan/2021 15:25:41] ================================================================================
Traceback (most recent call last):
  File "/home/pnoel/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pnoel/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/pnoel/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/pnoel/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/pnoel/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [22/Jan/2021 15:25:45] ================================================================================
Traceback (most recent call last):
  File "/home/pnoel/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pnoel/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/pnoel/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/pnoel/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/pnoel/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.9.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
```
The error appears directly when I try to edit a python buffer

**Comment by dakra** [comment]
Hmm, in the exception it still says anaconda version `0.1.13`.

Try to update, and then either kill the anaconda process buffer of just restart Emacs.
Hopefully that bug is already fixed.

**Comment by dakra** [comment]
@xxxvik-xakerxxx do you still have the problem with the newest anaconda version?

**Comment by PhilippeNoel1** [comment]
With the new version it works for me.
